version: "2.1"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS:
        "INTERNAL://kafka:9090,\
         EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS:
        "INTERNAL://kafka:9090,\
         EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        "INTERNAL:PLAINTEXT,\
         EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  postgres:
    image: postgres:14.5
    container_name: postgres_container
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=0099
      #- PGADMIN_LISTEN_PORT=5050
      #- PGADMIN_DEFAULT_SERVER=postgres  # Add this line to automatically connect to the PostgreSQL server
      #- PGADMIN_DEFAULT_SERVER_HOST=postgres  # Add this line to specify the server host
      #- PGADMIN_DEFAULT_SERVER_PORT=5432  # Add this line to specify the server port
      #- PGADMIN_DEFAULT_SERVER_DATABASE=airflow  # Add this line to specify the default database
      #- PGADMIN_DEFAULT_SERVER_USERNAME=airflow  # Add this line to specify the default username
      #- PGADMIN_DEFAULT_SERVER_PASSWORD=airflow  # Add this line to specify the default password
    ports:
      - "5050:80"
    depends_on:
    - postgres

  webserver:
    image: puckel/docker-airflow
    restart: always
    container_name: server
    build: 
      context: .
      dockerfile: dags/dockerfile
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR = Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
